apiVersion: batch/v1
kind: Job
metadata:
  name: 'database-migration'
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: 'database-migration'
    spec:
      restartPolicy: Never
      containers:
      - name: database-migration-job
        image: "{{.Values.deploy.registry}}/cleanarchitecture/migrations:{{.Values.deploy.imageTag}}"
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        securityContext:
          runAsUser: 1000
          privileged: false
          allowPrivilegeEscalation: false
  backoffLimit: 0